import { Header } from "@/components/Header";
import { PostCard } from "@/components/PostCard";
import { Posting } from "@/components/Posting";
import { api } from "@/utils/api";
import { type NextPage } from "next";
import Head from "next/head";


const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Post on Your Fav Sosmed</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Content />
      </main>
    </>
  );
};

export default Home;

const Content: React.FC = () => {
  const { data: posts, refetch: refetchPosts } = api.post.getAll.useQuery();
  
  const vibrate = () => {
    window.navigator.vibrate([200, 100, 200])
  }

  const createPosting = api.post.create.useMutation({
    onSuccess: () => {
      void refetchPosts();
    },
  });

  const deletePosting = api.post.delete.useMutation({
    onSuccess: () => {
      void refetchPosts();
    },
  });

  return (
    <div className="mx-5 mt-5 grid grid-cols-4 gap-2">
      <div className="px-2">
      </div>
      <div className="cl-span-3">
        {posts?.map((post) => (
          <div key={post.id} className="mt-5">
            <PostCard post={post} onDelete={() => void deletePosting.mutate({id: post.id})} />
          </div>
        ))}
        <Posting
          onSave={({ title, content }) => {
            void createPosting.mutate({
              title,
              content,
            });
          }}
        />
      </div>
    </div>
  );
};
